# Generated by Django 5.0 on 2024-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=30)),
                ('PublisherName', models.CharField(max_length=30)),
                ('AuthorName', models.CharField(max_length=30)),
                ('EditionName', models.CharField(max_length=30)),
            ],
        ),
    ]
